### PR TITLE
Added structural length support for Array 

### PR DESCRIPTION
**Pull request by udhayasankari**
Updated code to support length within a structure can be used as array length. Added few acceptance tests to verify this as well.

### CODE REVIEW

**Comment by jussimalinen** [comment]
Okay, I see a few acceptance tests that have been commented out. What is the status of these? Do you plan to implement them in this same pull request or are they documentation for future improvements?

**Comment by udhayasankari** [comment]
Those commented out tests are supposed to work but it is not. So plan is to document and put it for future improvement. 

For now we can use structural length inside for array declaration.

**Comment by jussimalinen** [comment]
Okay, In general our approach has been that tests that are supposed to work, but dont yet, should be left to run but without the regression tag. This way they are visible but not failing the test run.

**Comment by udhayasankari** [comment]
Okay. I can uncomment the test and remove the regression tag as well.

**Comment by udhayasankari** [comment]
Hi , 

I have removed regression tag for those uncommented testcases. 
Will try to fix those testcases working and perform as separate enhancement.

**Comment by jussimalinen** [comment]
I can also take a look at this code later in the coming days. Are you working on this issue right now or is the latest code in the pull request?

**Comment by udhayasankari** [comment]
Latest code is available in the pull request. you can take a look at it

**Comment by jussimalinen** [comment]
Thanks! I made a couple of changes to support also the dynamic length from inside a struct.

**Pull request merged**
